### ISSUE TITLE
Joining forces with nodenv?

### ISSUE THREAD

**Issue by jasonkarns** [riywo/ndenv#10]
[nodenv](https://github.com/OiNutter/nodenv) is an rbenv fork for node that has an active group of maintainers (disclaimer: I am one of said maintainers) and is in the process of migrating to the [nodenv github org](https://github.com/nodenv). We also perform regular merges down from rbenv upstream, to stay abreast of the latest rbenv bug fixes and features.

I see that ndenv is also an rbenv fork. Are there features that have been added to ndenv that are lacking in rbenv from which nodenv could benefit? Are you interested in joining forces and adding any ndenv features to nodenv (and perhaps sunsetting ndenv in favor of nodenv)?

(I realize that opening an issue against a project and suggesting that said project be sunset is rather brash. But I mean no offense and only suggest this so as to unify the rbenv-for-node community. Indeed, this has already taken place one with the merging/deprecating of [wfarr's nodenv](https://github.com/wfarr/nodenv) into/in favor of [oinutter's nodenv](https://github.com/OiNutter/nodenv).)

**Comment by mmartinson** [comment]
It would be great to at least link in the README to the more widely used and better maintained alternatives.

**Comment by riywo** [comment]
Done! https://github.com/riywo/ndenv/commit/6ee484077e7defb3151b5455d129ae01a804efe4
